# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7f4b971792142073e08147afef7f42294cf206fcfeee5122431be8d6a11ea7472730826998c7f37acf82564b404ba0f7c3606a3b3a709a1043bf02b95dd82b0

test:
  secret_key_base: 74c8df46b6f37d7ae841910f511e6d808f5277a23172ade7407ae1ff7425c1583f214f37b88a80720441462b10477a2c1b3d15b132a99e2526c5c4abe965bcdc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
